### ISSUE TITLE
Get raw array representation of the positions?

### ISSUE THREAD

**Issue by gre** [yo35/kokopu#13]
Is there a way to do like what .ascii() is doing but actually returning an array of size 64 that can be used programmatically

Thanks

**Comment by yo35** [comment]
Hi,
There is `.square(<square>)` that returns the content of the given square. For instance: `.square('e4')`.
There is no way to return the content of all the 64 squares in a single call.

Full documentation available here: https://kokopu.yo35.org/docs/
