### ISSUE TITLE
Possible features

### ISSUE THREAD

**Issue by mbutsykin** [yo35/kokopu#22]
Loving your creation!
Is there any chances you are planing on adding `promote` & `remove` variation / node?

**Comment by mbutsykin** [comment]
This is awesome! Thank you a lot, i bet for `promote` you will need to store references to parent variation, therefore - maybe you can add `prev` reference to the previous node in _nodeInfo?

**Comment by yo35** [comment]
The following methods have been added in 2.3.0 to manage the variations:
- `Node#promoteVariation()`
- `Node#swapVariations()`
- `Node#removeVariation()`
- `Node#removeFollowingMoves()`
- `Variation#clearMoves()`

See the [documentation](https://kokopu.yo35.org/docs/) for details on these methods.
