### ISSUE TITLE
InvalidPGN -> [133] Unknown chess game variant (Standard).

### ISSUE THREAD

**Issue by ArneVogel** [yo35/kokopu#3]
When trying to load a pgn from lichess I get this error:

InvalidPGN -> [133] Unknown chess game variant (Standard).

The pgn to reproduce the error: https://lichess.org/study/KTzlXH6b.pgn

**Comment by yo35** [comment]
Hi,
Thanks for reporting. This is fixed in version 1.2.2 (just released).
