### ISSUE TITLE
Comments are ignored if cls or cal information exists on the same move

### ISSUE THREAD

**Issue by ArneVogel** [yo35/kokopu#4]
Example study: https://lichess.org/study/D6DfYHZe 

Lichess exports this pgn with the comment and cal/cls on the same move as such: 

`1. e4 { this is a comment } { [%csl Gd5,Gf5][%cal Ge4d5,Ge4f5] } *`

kokopu picks up the csl/cal information but ignores the comment https://i.imgur.com/VpW6NB7.png

**Comment by yo35** [comment]
Fixed in version 1.2.3 (just released). Thanks for reporting.
