### ISSUE TITLE
How to get fen in PGN parsing ?

### ISSUE THREAD

**Issue by shooter01** [yo35/kokopu#41]
I am trying to parse pgn and get the fen, but don't see any mention in (parsed.game(0)
```
const { pgnRead } = require('kokopu');
const parsed = pgnRead(multerText);
console.log(parsed.game(0));
```

How to get starting fen from this tag ?
[FEN "4r1k1/1q3ppp/p7/8/Q3r3/8/P4PPP/R3R1K1 w - - 0 1"]

**Comment by yo35** [comment]
```
console.log(parsed.game(0).initialPosition().fen())
```

See https://kokopu.yo35.org/docs/4.7.0/classes/Game.html for more details.

**Comment by shooter01** [comment]
thank you, it works
