### ISSUE TITLE
Get/Set Pieces in Position

### ISSUE THREAD

**Issue by LocutusOfPenguin** [yo35/kokopu#47]
Hi,

i would like to get the pieces of a square, or set it to something. Is that possible?

SImilar to chess.js. There i can use this:
.put(piece, square)
.remove(square)

Thanks.

**Comment by yo35** [comment]
That would be for instance:

```
position.square('e4', 'wp');
position.square('d1', '-');
```

More example here:
https://kokopu.yo35.org/docs/current/documents/Tutorials.Set_up_a_position.html

Documentation on the `Position` class available here:
https://kokopu.yo35.org/docs/current/classes/Position.html

**Comment by LocutusOfPenguin** [comment]
Thanks.
I overlooked this "setup" , incl. "let piece = position.square('a2')"

Great lib btw, esp cause it supports chess960.
