### ISSUE TITLE
InvalidPGN Unrecognized character or group of characters

### ISSUE THREAD

**Issue by ArneVogel** [yo35/kokopu#6]
InvalidPGN -> [350] Unrecognized character or group of characters.

Link to study: https://listudy.org/static/pgn/rglLKTF.pgn

When I replace the '0''s (Zeros) with 'O' (the character o) for the castling it gets parsed correctly.

**Comment by ArneVogel** [comment]
It seems like the pgn is not standard complaint ( http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.2.3 see 8.2.3.3: Basic SAN move construction ). So not a bug in your library but maybe a nice to have feature.

**Comment by yo35** [comment]
Hi,
This issue has already been discussed: yo35/rpb-chessboard#142

To cut a long story short, I'm not very comfortable with the idea of making the parser tolerant to this kind of error in the PGN, as it would introduce some additional complexity to it, meaning additional maintenance effort, possibly more bugs, and it clearly goes against the PGN standard.

A question by the way: what is the origin of this ill-formed PGN file? Which software has generated it? (if any)

**Comment by ArneVogel** [comment]
I asked the person who uploaded the pgn but they didnt answer/know where they got it from. They said it was a file on their pc. 

Makes sense why you dont want to support that. I will close the issue.

**Comment by ArneVogel** [comment]
They just told me the pgn came from the android app "Blieb chess recorder"

**Comment by yo35** [comment]
It appears that the FIDE handbook recommends to use character 0 (zero) for castling moves: see https://handbook.fide.com/chapter/E012018 (section C.13). This may explain why the PGN files generated by some software disobey the PGN norm on this point.

For this reason, I changed my mind. OK to support zero-encoded castling moves.

**Comment by yo35** [comment]
Done in version 1.10.2
