### ISSUE TITLE
InvalidPGN -> [0] Unrecognized character or group of characters.

### ISSUE THREAD

**Issue by ArneVogel** [yo35/kokopu#7]
PGN that creates the error: https://listudy.org/static/pgn/JZ3aIG2.pgn
Works fine after importing -> exporting it from lichess: https://lichess.org/game/export/GUOmELUs?evals=0&clocks=0

The erroneous PGN came from ChessBase: https://github.com/ArneVogel/listudy/issues/7

**Comment by yo35** [comment]
Hi,
The problem comes from the fact thar there is an invisible character called "byte order mark" at the beginning of the PGN file. More on this issue in:
https://en.wikipedia.org/wiki/Byte_order_mark
https://www.freecodecamp.org/news/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7/

**Comment by yo35** [comment]
Fixed in version 1.2.5
